### PR TITLE
Rebase Trees and avoiding linearisation of rebased commits

### LINKED ISSUE #59: Tree rebases linearize commit tree
Caused by: https://github.com/taneliang/stack-attack/blob/5155a84933dc316a50328b5f84b20c655a25365d/src/source-control/GitSourceControl.ts#L326-L327

Found at https://github.com/taneliang/stack-attack/pull/42#discussion_r470998359

This bug is easier to explain with repro steps:

1. Have some commits on master: 
image
1. Rebase C (`c265a2`) onto B (`0952ea`). This works: a new C is created and all the local branches are moved onto it.
image
1. Rebase B (`0952ea`) onto A (`54c20d`)
	
	The UI right before pressing `c` to confirm the rebase:
	
	image

	After rebase:

	image

	2 new "C" commits are created. This is likely because the line linearized the tree, applying both the local and remote C commits (`3fb693` and `c265a2`) on each other instead of applying both onto B.

This bug should also be reproducible when you rebase any tree, not just trees with remote branches.

### PR DESCRIPTION
**Pull request by saphal1998**
# Summary

Resolves #59 

This approach helps us to rebase trees rather than linearising them as we have been so far, which is a major bug in the rebase implementation.

We use a hashmap to keep track of the target commit hash. This allows us to select the commit to be rebased on. The use of the hashmap allows us to rebase arbitrary trees and retain their structure on the target commits, hence almost identically mimicking a rebase.

# Testing plan

- Initial State

On Stack Attack
stack-attack-initial
On Git Logs
git-initial

- Final State

Upon rebasing `4d78fd` (Commit Message: 2nd File) on `5b244c` (Commit Message: 4th File), we get

On Stack Attack
stack-attack-final
On Git Log
git-final 

# Notes

This still does not solve the problem of merge commits which can have multiple parents, as can be seen in the line `rebaseTargetHashMap.set(childCommitHash, newCommitOid.tostrS())`. In the case of merge commits, the merge commit's parent will be resolved to an indeterminate parent, which may be a bug to be addressed in the future.

### CODE REVIEW

File: src/source-control/GitSourceControl.ts [hunk 1]
```diff
@@ -230,10 +234,19 @@ export class GitSourceControl implements SourceControl {
...
-      const hashToBeRebased = queue.pop()!;
+      const hashOfCommitToBeRebased = queue.pop()!;
+      // `hashOfCommitToBeRebased` should always be present in the rebaseTargetHashMap, adding nullthrows here, so that if null,
+      // rebase cannot happen
+      targetCommitHash = nullthrows(
+        rebaseTargetHashMap.get(hashOfCommitToBeRebased),
+        `Target commit for ${hashOfCommitToBeRebased.slice(
+          0,
+          6,
+        )} could not be found `,
```
Comment (taneliang) [inline src/source-control/GitSourceControl.ts]: Nit: should we dump the slicing since we don't truncate hashes in other errors?

```suggestion
        `Target commit for ${hashOfCommitToBeRebased} could not be found`,
```

File: src/source-control/GitSourceControl.ts [hunk 2]
```diff
@@ -326,9 +339,10 @@ export class GitSourceControl implements SourceControl {
 
       queue.push(...commitToBeRebased.childCommits);
 
-      // We now would want to use this new commit hash as the target
-      // FIXME: This will turn a commit tree into a linear stack!
-      targetCommitHash = newCommitOid.tostrS();
+      // We now would want to use this new commit hash as the target for all of it's children
```
Comment (taneliang) [inline src/source-control/GitSourceControl.ts]: Nit: rephrasing for clarity+grammar (imo, feel free to change further)

```suggestion
      // Register new commit as the rebase target for all children
```

File: src/source-control/GitSourceControl.ts [hunk 3]
```diff
@@ -326,9 +339,10 @@ export class GitSourceControl implements SourceControl {
...
+      commitToBeRebased.childCommits.map((childCommitHash: CommitHash) => {
```
Comment (taneliang) [inline src/source-control/GitSourceControl.ts]: Nit: prefer `forEach` over `map` when we don't care about the return value. Also since TS already knows the type of `childCommitHash` so it's not strictly necessary to specify it, removing it will reduce the amount of cognitive load imo

```suggestion
      commitToBeRebased.childCommits.forEach((childCommitHash) => {
```

**Review by taneliang — APPROVED** [review]
Looks great! Just some nits, then let's get this merged 🎉 

Screenshots from my manual test, where I rebased B3 onto B2:

Before

image

After

image

File: src/source-control/GitSourceControl.ts (hunk 1 above)
Comment (saphal1998) [reply src/source-control/GitSourceControl.ts]: Yeah, I think I just did that to make it readable. I actually think we should truncate all the error logs to display truncated commit hashes.
